version: '3.8'

services:
  evenement-api:
    container_name: evenement-api
    build:
      context: ./gestionEvenement
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
  
  membre-api:
    container_name: membre-api
    build:
      context: ./gestionMembre
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    restart: always

  lieu-api:
    container_name: lieu-api
    build:
      context: ./gestionLieu
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always


