version: '3.8'

services:
  evenement-api:
    container_name: evenement-api
    build:
      context: ./gestionEvenement
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    networks:
      - my_network

  membre-api:
    container_name: membre-api
    build:
      context: ./gestionMembre
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    restart: always
    networks:
      - my_network

  lieu-api:
    container_name: lieu-api
    build:
      context: ./gestionLieu
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    networks:
      - my_network

  commentaire-api:
    container_name: commentaire-api
    build:
      context: ./GestionCommentaire
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: always
    networks:
      - my_network    

  docs-api:
    image: swaggerapi/swagger-ui
    container_name: docs-api
    ports:
        - "8086:8080"
    volumes:
        - ./docs:/usr/share/nginx/html/docs
    environment:
        API_URL: ./docs/doc.json
    networks:
      - my_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    networks:
      - my_network
  
  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - membre-api
      - evenement-api
      - lieu-api
      - commentaire-api
      - docs-api
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
