version: '3.8'

services:
  evenement-api:
    container_name: evenement-api
    build:
      context: ./gestionEvenement
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
  
  membre-api:
    container_name: membre-api
    build:
      context: ./gestionMembre
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Utiliser un autre port si nécessaire
    restart: always


